example:
  property: I AM DEV

eureka:
  client:
    service-url:
      registerWithEureka: "true"
      fetchRegistry: "true"
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: "true"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://postgres:5432/booking_db #For docker localhost = postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update