example:
  property: I AM THE DEFAULT

server:
  port: 8084

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.akuev: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,routes
      base-path: /actuator
  endpoint:
    gateway:
      access: read-only
    health:
      show-details: always
      access: read-only
    routes:
      enabled: true
      access: read-only
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
        routes:
          - id: movieservice
            uri: http://localhost:8081
            predicates:
              - Path=/movie/**
            filters:
              - RewritePath=/movie/(?<path>.*), /$\{path}
              - RemoveRequestHeader=Cookie,Set-Cookie

          - id: bookingservice
            uri: http://localhost:8083
            predicates:
              - Path=/booking/**
            filters:
              - RewritePath=/booking/(?<path>.*), /$\{path}
              - RemoveRequestHeader=Cookie,Set-Cookie              

          - id: userservice
            uri: http://localhost:8082
            predicates:
              - Path=/user/**
            filters:
              - RewritePath=/user/(?<path>.*), /$\{path}
              - RemoveRequestHeader=Cookie,Set-Cookie

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

