example:
  property: I AM THE DEFAULT

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,routes
      base-path: /actuator
  endpoint:
    gateway:
      access: read-only
    health:
      show-details: always
      access: read-only
    routes:
      enabled: true
      access: read-only

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
        routes:
          - id: movieservice
            uri: lb://movieservice
            predicates:
              - Path=/movie/**
            filters:
              - RewritePath=/movie/(?<path>.*), /$\{path}

          - id: bookingservice
            uri: lb://bookingservice
            predicates:
              - Path=/booking/**
            filters:
              - RewritePath=/booking/(?<path>.*), /$\{path}

          - id: userservice
            uri: lb://userservice
            predicates:
              - Path=/user/**
            filters:
              - RewritePath=/user/(?<path>.*), /$\{path}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/