example:
  property: I AM THE DEFAULT

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,routes
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
    routes:
      enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/