example:
  property: I AM THE DEFAULT

app:
  internal:
    api-key: "cinema-internal-secret-key-2024"

server:
  port: 8081

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.akuev: DEBUG
    org.springframework.security: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cinema #For docker localhost=keycloak
          jwk-set-uri: http://keycloak:8080/realms/cinema/protocol/openid-connect/certs #For docker localhost=keycloak
  cloud:
    stream:
      bindings:
        movieSessionOutput-out-0:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092
          auto-create-topics: true
          auto-add-partitions: true
          
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
        