example:
  property: I AM THE DEFAULT

server:
  port: 8081

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.akuev: DEBUG
    org.springframework.security: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cinema #For docker localhost=keycloak
          jwk-set-uri: http://localhost:8080/realms/cinema/protocol/openid-connect/certs #For docker localhost=keycloak