example:
  property: I AM THE DEFAULT

server:
  port: 8082

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true