example:
  property: I AM THE DEFAULT

server:
  port: 8082

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.akuev: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true